.PHONY: start unit integration tests startIntegrationClient

start:
	@npm start

unit:
	@npm test

integration:
	@npm run integration

tests: unit integration

startIntegrationClient:
	@npm run startIntegrationClient
